language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=0
    - WP_VERSION=4.3.1 WP_MULTISITE=0

install:
    - composer install

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
